### ISSUE TITLE
Implement nightly builds

### ISSUE THREAD

**Issue by TheBloke** [DFHack/dfhack#762] opened 2015-11-26 23:51 UTC
It would be handy if we had automatic nightly builds, built whenever commits are made to Develop.

This would provide a convenient place for both developers and users to get the latest code without having to build, and would provide an easy source for inter-release fixes for packs such as PE's Windows Starter Pack.

We already have Travis that does automatic builds on Linux  - I imagine we could find a way to distribute the resulting files.  Perhaps by adding a tar & upload command to the end of the existing build script, uploading to Github releases.

Or, potentially much better, there's this:  [Nightli.es: "provides automatic nightly builds for Travis CI."](https://nightli.es/)

For Windows and OSX: I run both concurrently and my PC is on 24/7, so I'd be happy to have a script running in the background of both OS' that checks Travis for successful builds and git pulls, builds and uploads the resulting file. 

We could make the script to do that available in the repo and potentially multiple contributors could add it on a schedule, to share the load/add redundancy - with some kind of checking in the script so the release is only built once.

And/or maybe some DFHack contributors have access to proper Windows and/or OSX servers that could run such a script - perhaps a work server they administer (and are allowed some freedom on.)

Thoughts?

**Comment by lethosor** [comment] 2015-11-26 23:56
I think we'd be able to build OS X builds on Travis as well, although the lack of container-based infrastructure would make it a bit slower (it would need to boot each time, from what I understand).

**Comment by TheBloke** [comment] 2015-11-27 00:02
That'd be great!

**Comment by PeridexisErrant** [comment] 2015-11-27 01:28
Nightly builds would be great, especially if individual plugins can run under the latest release (which should usually work, I think).  I'm very unlikely to ship a whole nightly though - too difficult to reproduce problems and clearly document which version - so more frequent releases would also be nice :)

**Comment by lethosor** [comment] 2015-11-27 01:49
#761!
Anyway, plugins on the develop branch aren't always compatible with the last release - workflow isn't, for example, because it relies on core changes (structure changes don't matter, though, at least with the same version of DF).

**Comment by PeridexisErrant** [comment] 2015-11-27 03:14
I know :)

Yep, hence "usually".  I think `confirm` would have worked though, right?

**Comment by lethosor** [comment] 2015-11-27 04:13
Yeah, although it would have required adding `hack/lua/plugins/confirm.lua` and `hack/scripts/gui/confirm-opts.lua` as well, so it wouldn't have been quite as simple.

**Comment by warmist** [comment] 2016-03-04 09:37
We can use the free services to build our nightlies (because we don't care about speed that much).
One for travis: https://docs.travis-ci.com/user/deployment/releases/
One for appveyor (windows):  https://www.appveyor.com/docs/deployment/github

I pretty sure i saw some opensource projects using them for free for nightly builds.

**Comment by BenLubar** [comment] 2020-01-28 17:41
@lethosor the latest DFHack core build is available at `https://buildmaster.lubar.me/api/ci-badges/link?page=build&key=badges&$ApplicationId=3`

I think this issue is safe to close as we've been using BuildMaster pretty consistently for the last year or so.

**Comment by lethosor** [comment] 2020-01-28 19:32
We could probably advertise it a little better in the docs, but yeah, that's functional.
I thought about making an easier-to-navigate front-end on dfhack.org but haven't gotten around to it

**Comment by lethosor** [comment] 2020-04-04 04:46
Wound up on this again from the labels list; yup, agree that we can close this!

**Closed by lethosor** 2020-04-04 04:46 UTC
Labels: idea, travis
