### ISSUE TITLE
Exporting: extra legends_plus xml error

### ISSUE THREAD

**Issue by winjester** [DFHack/dfhack#1364] opened 2018-07-15 15:22 UTC
![1](https://user-images.githubusercontent.com/41267014/42735410-53d4fae4-8821-11e8-92cb-1a218f728dd4.png)

color: meph
Tileset: Meph - 32x32
if that matters

**Comment by lethosor** [comment] 2018-07-15 19:47
What DFHack version?

**Comment by winjester** [comment] 2018-07-15 21:08
The version that comes with Masterwork Dwarf Fortress 1.29
version 5.84 i think.
it might be just that save that is bad, i have made new worlds on a fresh copy of Masterwork and they all export just find.

**Comment by lethosor** [comment] 2018-07-15 21:20
"5.84" is not a DFHack version. Can you run "help" in the DFHack console and paste the output?

**Comment by winjester** [comment] 2018-07-15 21:22
I see it , DFHack version 0.43.05-rl (release) on x86_64

**Comment by lethosor** [comment] 2018-07-15 21:30
0.43.05-r1? That's very old (not even close to the last version for 0.43.05), and unsupported. I'm pretty sure this is a duplicate of #1213, which was [fixed in 0.44.04-alpha1](https://github.com/DFHack/scripts/commit/bd8fbdd78b6bc1321ab00601d5b4e4f0c716b3e2) (that change ought to work for you too, although the line numbers might be a bit off).

**Closed by lethosor** 2018-07-15 21:30 UTC
