### ISSUE TITLE
Dwarfvet causes game crash

### ISSUE THREAD

**Issue by bessgeor** [DFHack/dfhack#1270] opened 2018-05-13 13:05 UTC
### Software in use
- PyLNP win x64 0.13
- DF 0.44.09
- DFHACK 0.44.09-r1 (release) on x86-64
- TWBT 6.41

### Problem
Running `dwarfvet enable` causes the game to crash after some ticks.

### Steps to reproduce
Download [my save](https://files.fm/f/x9rjfnq9), run it, run `dwarfvet enable`, wait a couple of seconds.

[Original issue in the plugin repo](https://github.com/NCommander/dfhack-dwarfvet/issues/2)

**Comment by lethosor** [comment] 2018-05-14 18:33
From #1272: https://drive.google.com/file/d/1_sHgznx1Bqz_LHqJvsP-w95W3uou5Biq/view?usp=sharing

**Comment by lethosor** [comment] 2018-05-17 00:45
@bessgeor I haven't gotten your save to crash in 0.44.10 (osx64) yet, using DFHack 0.44.10-beta1. Does it happen for you in that version?

Also, I'm getting this logged to the DFHack console around once a second:
```
Telling intelligent unit 7511 to report to the hospital!
Telling intelligent unit 7512 to report to the hospital!
Telling intelligent unit 8008 to report to the hospital!
Telling intelligent unit 8010 to report to the hospital!
```
as well as these announcements in-game:
```
Stray hunting Dog (Tame) cancels Rest: Area inaccessible.
Stray war Dog (Tame) cancels Rest: Area inaccessible.
```
Did you see any of those before the crash?

**Comment by bessgeor** [comment] 2018-05-17 16:42
@lethosor I don't know how to run 0.44.10 until new PyLNP release.

I have been getting the following logs on .09 just before the crash:
```
[DfHack]# dwarfvet enable
Populating hospital cache:
    Found animal hospital 11186  at x1: 137, y1: 161, z: 52 from valid hospital list
Accepted patient 7511 at hospital 11186
Accepted patient 7512 at hospital 11186
Accepted patient 8008 at hospital 11186
Accepted patient 8010 at hospital 11186
Telling intelligent unit 7511 to report to the hospital!
Telling intelligent unit 7512 to report to the hospital!
Telling intelligent unit 8008 to report to the hospital!
Telling intelligent unit 8010 to report to the hospital!
```

[Here](https://i.imgur.com/rFq34hk.jpg) is a screenshot of those, and [here](https://videobin.org/+skk/xd5.html) is a video of the crash (may take some time to be processed by the hosting. Logs and crash at 0:22).

**Comment by JezaGaia** [comment] 2018-05-19 16:09
I had the same crash also in 0.44.09, haven't tried in 0.44.10 as I haven't downloaded it yet.
I don't have the save anymore unfortunately but here is what happened : 
I had a hospital, functioning properly for adwares and humans.
I added training to the zone, I also made certain I had some animal caretakers.
I launched Dwarfvet
I had the message about 
"Animal" (Tame) cancels Rest: Area inaccessible. 
The game kept running without issues except that message was repeated on and on.
I thought about the fact that the cat was pastured in a zone. I removed him from that zone and then the game crashed

I reloaded, I re added the zoning in the hospital but also un-pastured the hurt cat before I launched dwarfvet and that time the game crashed right away.

So it seems to me that it's when the cat actually went or tried going to the hospital that the problem happened not when he couldn't access it.

Hope this helps, as soon as I get on the next version I'll give it another try and let you know if it worked or not.

**Comment by suokko** [comment] 2018-06-19 17:15
Does dwarvet work with 44.10?
At least I couldn't get it work when using 44.10 and the linked save.

**Comment by lethosor** [comment] 2018-06-19 17:18
I don't know if it works or not. But @bessgeor and @JezaGaia, did either of you test to see if it crashes in 0.44.10-r1?

**Comment by JezaGaia** [comment] 2018-06-19 17:48
Sorry I had completely forgotten to come back to report.
I tested it a couple of weeks ago and it still crashes.
I was paying more attention and can tell you that the dog that was hurt went to the hospital and the dwarf went to attend him and it's when the dwarf reached the dog that it crashed.
It went too fast for me to see if it was when beginning to heal the dog or after he was treated though.

**Comment by suokko** [comment] 2018-06-19 18:07
Can you upload a save where reproducing the issue is easy?

There can be some other bugs which prevented me from reproducing the with the linked save.

**Comment by JezaGaia** [comment] 2018-06-19 18:34
It'll take me a couple of days as my fort is now dead due to computer upgrade, yep that's a new megabeast that appears and eats your saves when you mess up and don't properly backup your hardrive before upgrading your CPU :(
But as soon as I have a new one running I'll try again and post the save

**Comment by aljfdbgaliudhfbn** [comment] 2018-08-12 16:38
Running "dwarfvet enable" on 44.12 with the current dfhack on mac just crashed my game too.

**Comment by hrobertson** [comment] 2019-06-04 21:21
Repeatably crashing on DFHack version 0.44.12-r2 (release) on x86_64

I was able to (mostly) avoid crashes by unassigning the Animal Training labour from all dorfs and unassigning the Animal Care labour from all but one.
If I assigned Animal Training to a dwarf other than the one with Animal Care, the game crashed within about 20 steps. (This was while there were animals being tended to.)

**Comment by myk002** [comment] 2024-03-14 05:25
Fixed in https://github.com/DFHack/dfhack/pull/3877

**Closed by myk002** 2024-03-14 05:25 UTC
Labels: crash/hang
