### ISSUE TITLE
Unknown Job 241 ... labormanager

### ISSUE THREAD

**Issue by DerpnHurdles** [DFHack/dfhack#1601] opened 2020-07-02 09:00 UTC
My terrible militia commander has had an unknown job issue, turns out the cheeky mongrel was looking to steal an artifact!

Last time I got this error, it was related to a Justice task that had no office to be done in.  Seems like a similar circumstance except I have built the office before this cropped up.

Edit:
an update

LABORMANAGER: job has no job to labor table entry: ?241? (241)
LABORMANAGER: job has no job to labor table entry: ?243? (243)
Dwarf "elimusekanen" has unknown job 241

He is now dancing with a goblin outside the tavern...

**Comment by DerpnHurdles** [comment] 2020-07-02 09:17
Hell, I just had a thought, It's an instrument that he has picked up, and he's dancing with a goblin... is he.. making overt proposals to the goblin?

**Comment by quietust** [comment] 2020-07-02 12:03
Jobs 241 and 243 are defined in df-structures as "unk_fake_no_job" and "unk_fake_no_activity", since they show up as "No Job" and "No Activity", respectively. Both are classified as Crimes, though we don't actually know _which_ crimes those are - given your findings, at least one of them is a theft attempt.

**Comment by lethosor** [comment] 2020-07-02 13:58
Yeah, it's a duplicate of #1561 - the fix should be part of the next DFHack release, but isn't in 0.47.04-r1. You can grab a nightly build from https://dfhack.org/builds/ if you want to try it out - in this case you could probably copy just the labormanager plugin from one into the hack/plugins folder of your current installation.

**Closed by lethosor** 2020-07-02 13:58 UTC
Labels: labormanager

**Comment by DerpnHurdles** [comment] 2020-07-03 00:03
Thank you for your help and information.

Elim has now returned the instrument after his wild dancing, and everything is back to usual chaos.  Fun resumes.
