### ISSUE TITLE
advfort: "Operate pump" does not work

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#1611] opened 2020-07-21 17:16 UTC
When in advfort mode and standing on the operation tile of a screw pump, pressing tab to "Operate Pump" does nothing. There's no skill increase and no console error log as well as no actual pump operation.

**Comment by warmist** [comment] 2020-07-22 05:46
Reproduced. Does not look like something simple (i.e. job created, etc...) Afaik it used to work. Might be related to new job postings and co [More info here](https://github.com/DFHack/df-structures/issues/387)

**Comment by warmist** [comment] 2020-07-22 11:09
Should be fixed by [this pull-req](https://github.com/DFHack/scripts/pull/160)

**Comment by quietust** [comment] 2020-07-22 13:01
It makes sense that the job doesn't complete, since that's how it works In Fortress mode - to make it temporary, it might be enough to clear the `pump_manually` flag after a certain amount of time has passed.

**Closed** 2020-07-23 02:13 UTC
Labels: bug
