### ISSUE TITLE
the "craft-age-wear" tweak crashes Fortress Mode when unpaused

### ISSUE THREAD

**Issue by scamtank** [DFHack/dfhack#936] opened 2016-05-28 23:21 UTC
Nothing else that's enabled by default in dfhack.init-example seems to cause problems.

**Comment by lethosor** [comment] 2016-05-28 23:32
What DF version?

**Comment by lethosor** [comment] 2016-05-29 00:15
I couldn't reproduce this in the saves I have around in 0.43.03.

**Comment by scamtank** [comment] 2016-05-29 00:36
43.03, running a fresh 43.03-alpha0 compile that I built earlier today. The git version is 0.42.06-r1-65-g4d3df60. I zipped it up for reference. https://dl.dropboxusercontent.com/u/7025840/dfhack43.03-alphazero.7z

**Comment by lethosor** [comment] 2016-05-29 00:45
I can't use that because I'm not on Windows, and that appears to be a merge commit you made yourself and haven't pushed.
Anyway, given that hardly anything has changed today, except that PR being merged, it's more likely that it's a save-specific issue than anything else, so can you upload the save?

**Comment by scamtank** [comment] 2016-05-29 00:55
Sure, here's one. https://dl.dropboxusercontent.com/u/7025840/save.7z

I verified that it happens with this fresh world with stock raws too. As soon as I type "tweak craft-age-wear" in the console (or unpause after enabling the script), it crashes instantly.

**Comment by lethosor** [comment] 2016-05-29 00:59
What xml edits?

**Comment by scamtank** [comment] 2016-05-29 01:03
None, that's the end of it. I didn't alter anything else, at least not intentionally.

**Comment by lethosor** [comment] 2016-05-29 01:03
I couldn't reproduce this in a fresh world in 0.43.03. Also, if "tweak craft-age-wear" is in dfhack.init, it will be enabled on startup, so running "tweak craft-age-wear" again will do nothing. Are you sure that's what the problem is?

**Comment by lethosor** [comment] 2016-05-29 01:06
Your save also doesn't crash for me after loading it, unpausing, and running `tweak craft-age-wear` several times.

**Comment by scamtank** [comment] 2016-05-29 01:08
Yes, I got a handle on it only after commenting out everything in dfhack.init that wasn't keybinds on a whim and noticing that it wasn't crashing anymore. When I started going down the list and manually enabled each script in turn, it snagged on craft-age-wear again. I then re-enabled everything else in the .init except for that one script and it ran fine (until I ran it manually and crashed the thing instantly, of course).

**Comment by lethosor** [comment] 2016-05-29 01:10
With that save?

**Comment by scamtank** [comment] 2016-05-29 01:15
Yes, with that save.

Speaking of that save, the compile for the current code finished just now. I deleted every trace of prior DFHack and dropped this build in its place (Git: 0.42.06-r1-67-g113325f) and started up that same save that I just sent you, starting up from the dfhack.init-example provided. Boom, crashed again.

It's getting strange. Is there anything else I can give you?

**Comment by lethosor** [comment] 2016-05-29 01:31
I don't really know what the issue is. It's possible that it's a layout that changed only on Windows since 0.43.02, but that's pretty unlikely, and I don't think anyone else has reported this on 0.43.03 yet.
It could also be a bad vtable address. Can you see if running `:lua ~df.item_crafted:new()` works or crashes?

**Comment by scamtank** [comment] 2016-05-29 01:35
It didn't seem to upset anything. The console spat this out without a hitch.

`[DFHack]# :lua ~df.item_crafted:new()
<item_crafted: 0x08a3f548>
pos                      = <coord: 0x08a3f54c>
flags                    = <item_flags: 0x08a3f554>
flags2                   = <item_flags2: 0x08a3f558>
age                      = 0
id                       = 0
specific_refs            = <vector<specific_ref*>: 0x08a3f564>
general_refs             = <vector<general_ref*>: 0x08a3f574>
world_data_id            = -1
world_data_subid         = -1
stockpile_countdown      = 0
stockpile_delay          = 0
unk2                     = 0
base_uniform_score       = 0
walkable_id              = 0
spec_heat                = 0
ignite_point             = 0
heatdam_point            = 0
colddam_point            = 0
boiling_point            = 0
melting_point            = 0
fixed_temp               = 0
weight                   = 0
weight_fraction          = 0
stack_size               = 1
history_info             = nil
magic                    = nil
contaminants             = nil
temperature              = <temperaturest: 0x08a3f5bc>
wear                     = 0
wear_timer               = 0
anon_1                   = -1
temp_updated_frame       = -1
mat_type                 = -1
mat_index                = 0
maker_race               = -1
quality                  = 0
skill_used               = -1
maker                    = -1
masterpiece_event        = -1`

**Comment by BenLubar** [comment] 2016-05-30 20:43
I'm able to reproduce the crash with release mode on Windows but not debug mode.

**Comment by lethosor** [comment] 2016-06-13 21:03
Does the crash occur before or after the `[DFHack]#` prompt returns?

**Comment by NCommander** [comment] 2016-06-14 00:35
I can't reproduce this on Windows 43.03 with the latest build in either release or debug mode. I just smashed a bug related a crash related to eventful. I don't think know if it was related but can you please retest this with the latest develop branch? If you can still reproduce it, then I can try to debug it from a crash dump.

**Comment by scamtank** [comment] 2016-06-14 01:35
I... I can't! I pulled the current state of things as of 10 minutes ago (revision 9021fca) and activating the tweak doesn't crash the game instantly anymore. Just to check it wasn't a fluke, I threw in the compile I used at the time of this report (revision 4d3df60) and loaded the same save. Crash.

The environment I've been building these with has been unchanged through this. Whatever was causing it, it must've been unscrewed somewhere in the past 17 days.

**Comment by NCommander** [comment] 2016-06-14 01:41
@scamtank there's a good chance this got fixed by accident along the way. I'm going to disassemble the vtable entry related to craft-age-wear in a bit to confirm the prototype is correct (since this type of bug tends to crash Windows more frequently than Linux/OS X for unknown reasons), but I think its safe to close this one.

**Closed** 2016-06-14 01:45 UTC
Labels: crash, structures
