### ISSUE TITLE
 [DFHack] Lazy Mac Pack v0.47.04 Segfault Crashes

### ISSUE THREAD

**Issue by loloxchan** [DFHack/dfhack#1773] opened 2021-02-07 08:32 UTC
Hi all,

First-time poster here.

I am playing on Lazy Mac Pack v0.47.04, my game has been periodically crashing for no apparent reason for a long time, but now it seems the save is crashing around 6-7 secs after I launch the game, no matter what.

Here is the error message from the terminal:
[DFHack]# /Applications/Lazy Mac Pack v0.47.04 dfhack-b1/df_osx v0.47.04/dfhack: line 30: 64716 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

No relevant info on the terminal before that.
I uploaded the save to my drive, just wait a few secs for the crash to occur.
https://drive.google.com/drive/folders/1VKa3so7PBbeKhnbi-Vp49dijgxBFatTc?usp=sharing

I really hope to fix this save and keep playing, as the fortress has survived many years, would like to keep playing.
Any help appreciated <3

Best Lolo

P.S. I have loaded the save file to a native install of the original DF game (latest update 0.47.05), and the game is running fine.

**Comment by lethosor** [comment] 2021-02-07 16:07
Looks like a duplicate of https://www.bay12games.com/dwarves/mantisbt/view.php?id=11014 (related: #1678). Specifically, running `fix/corrupt-equipment` in DFHack 0.47.04-r5 prints a lot of things and allows the game to advance beyond when it would crash otherwise. The issue is mitigated to an extent in DF 0.47.05, which would explain what you saw there. `fix/corrupt-equipment` also fixes _some_ issues there (DFHack 0.47.05-alpha0-2-g06cd0c84), but not as many, and the game advances without running it.

**Closed by lethosor** 2021-02-07 16:07 UTC
Labels: out of scope
