### ISSUE TITLE
malformed keybinding invocations in onLoadWorld.init crash DFHack

### ISSUE THREAD

**Issue by TheBloke** [DFHack/dfhack#747] opened 2015-11-14 23:41 UTC
**Issue:** a malformed *keybinding* command executed in onLoadWorld.init will crash DF/DFHack when a game is loaded.  

* On Windows the window simply disappears - no crash message.   
* On Linux, it seg faults: ```Segmentation fault (core dumped)```

**Systems tested:**

* Windows 10, x64, DFHack downloaded from releases
* Linux, Ubuntu 15.04 x64, DFHack self-compiled (GCC 4.9)

**Replication steps**:

* DF 40.24
  * Windows: Customised init with Spacefox 16x16 art
  * Linux: Tested with the same, and also default init, art and raw files
* DFHack -r4, entirely as per release (no extra plugins added.)
* Only default DFHack config: ```dfhack.init.example``` renamed ```dfhack.init```; no other init except:
* Create ```onLoadWorld.init``` with the following single line:
```keybinding crashme```
* Run DF, load a save.  
  * On Windows: at the end of the normal DF loading, DF and DFHack windows will disappear.
  * On Linux, the same except it displays a segfault: ```Segmentation fault (core dumped)```
  * ```stderr.log``` last line will be ```keybinding crashme```
* Further tests performed:
  * Crash: Various other invalid keybinding commands
    * The original command that caused me to find this was mistakenly using: ```keybinding remove Ctrl-K``` instead of ```clear```
  * No Crash: Same command added to dfhack.init
    * shows expected "keybinding: usage" in DFHack console
  * No Crash: Other invalid commands not involving keybinding
    * ```workflow crashme```
    * ```fix-unit-occupancy crashme```
    * ```crashme```
    * all result in expected "Usage" display in Console.
* I have loaded multiple saves and multiple worlds, and three crashed and one did not
  * Specifically, I have two worlds available and I loaded two saves from each world
    * World 1: both saves crashed
    * World 2: one save crashed, the other did not.
  * It may therefore be related to information on-screen at the time?

Save game that will trigger the issue when ```onLoadWorld.init``` is created as described above: https://goo.gl/NdbnnN

Note that this save uses Modest Mod + Accelerated, which removes a lot of object information.  However the other world I tested is non-modded and crashed the same.

If required I can upload the save I tested that did not crash.

I have not yet tested this on -r3, only -r4.

**Comment by lethosor** [comment] 2015-11-15 01:50
The problem is the call to `Gui::getFocusString(Core::getTopViewscreen())`. For some reason, the vtable pointer in the top viewscreen is bad at that instant, which causes `virtual_identity::find(void *vtable)` to segfault.

**Comment by lethosor** [comment] 2015-11-15 02:38
Found the problem: `top_viewscreen` is only changed right before SC_VIEWSCREEN_CHANGED events are triggered, which happens *after* world and map-related events. This means that anything handling those events that refers to `top_viewscreen` is referring to the top viewscreen from the last tick, which was just deleted in this case.

**Comment by lethosor** [comment] 2015-11-15 02:52
Should be fixed now.
If you're curious, the root problem here dates back to at least 0.31.25, although I'm not aware of a way to trigger it prior to 0.34.11-r4, where initial support for onLoad.init scripts was added (9f6638432f28fa534a9045324516224b985ad0d3).

**Closed by lethosor** 2015-11-15 02:52 UTC
Labels: bug, crash

**Comment by TheBloke** [comment] 2015-11-15 12:53
Good job on the fast fix!
