### ISSUE TITLE
exportlegends: unknown identity_type (-1)

### ISSUE THREAD

**Issue by doloresjane** [DFHack/dfhack#1578] opened 2020-05-26 22:17 UTC
Hello, I am writing this in hopes that someone can get back to me, I have been exporting xml files and it says "unknown df.identity_type value encountered:-1. please report to DFhack team"
Not sure what the error is and I also had another a thing id like to ask, in the future could you include how to Report errors to you because when you read the readme it says we can help out by reporting errors but give no way to do so, i mean i figured it out but some other people might not be able to. just a thought, have a great day

**Comment by lethosor** [comment] 2020-05-27 00:40
@doloresjane thanks for the report! I have a fairly good guess what the `-1` is, but if you could upload the save somewhere so we can double-check, that would be appreciated (evidently we haven't seen that come up before).

Could you point me to the readme you mentioned that suggests reporting issues but doesn't give links? I haven't found a page that fits that description yet, but we're trying to improve our docs and would like to know if something is missing.

**Comment by doloresjane** [comment] 2020-05-27 14:35
I dont know how to show you the files... I can only google so much

**Comment by lethosor** [comment] 2020-05-27 14:44
You said:

> when you read the readme it says we can help out by reporting errors but give no way to do so

Can you give a link to the file you were looking at? Is it still in your browser history, maybe?

**Comment by doloresjane** [comment] 2020-05-27 17:02
I mean i dont know  how to upload a save to show you

**Comment by lethosor** [comment] 2020-05-27 17:49
http://dffd.bay12games.com/ is one site. There are also a bunch of other sites that would work - Google Drive, Box, Mediafire, Dropbox, etc. You would want to compress the specific folder (e.g. `data/save/region1`) containing your save and upload that.

Can you link to the readme you were looking at?

**Comment by doloresjane** [comment] 2020-05-28 05:15
http://dffd.bay12games.com/file.php?id=15098

**Comment by doloresjane** [comment] 2020-05-28 05:15
I hope I did it right, hopefully you can find something that will help your fix bugs, glad to help

**Comment by doloresjane** [comment] 2020-05-28 05:23
https://i.gyazo.com/e6ed47e3a3458d833fc4fa5a0ad5e52d.png this is the readme

**Comment by PatrikLundell** [comment] 2020-05-28 06:55
Weird. When I try to load the save (on Win64) DF crashes.

**Comment by doloresjane** [comment] 2020-05-28 08:07
I have the same problem but thats new... i have a copy but dont know if i lost everything

**Comment by doloresjane** [comment] 2020-05-28 08:10
I will see if i can get a working save tommorow not sure, sorry if i compressed wrong

**Comment by PatrikLundell** [comment] 2020-05-28 08:14
Thanks. It's not particularly urgent.

A side comment: It's possible to edit ("...") a post rather than multi posting (here as well as on the DF forum), cutting down a little on the clutter.

**Comment by doloresjane** [comment] 2020-05-28 15:55
They need to put you back in the mummy tomb cuz you're not a people person.

**Comment by PatrikLundell** [comment] 2020-05-28 15:58
Eh? What?

**Comment by ab9rf** [comment] 2020-05-28 17:18
Side note: the copyright date on the docs we stuff into published releases is 2015. We should probably update that, but I haven't found where that comes from yet.

**Comment by lethosor** [comment] 2020-05-28 18:13
I agree that the save is not particularly urgent. Given that `-1` in DF almost always represents `None`, I suspect that is the case here too. I'm just curious why we haven't run into it yet, and if there's something else going on with the identities that could cause other issues (e.g. the unit nickname logic elsewhere in DFHack).

Also, please avoid that kind of language here. I thought Patrik's advice was relevant, if unrelated to the issue itself, but ultimately we want to resolve the issue here.

> Side note: the copyright date on the docs we stuff into published releases is 2015. We should probably update that, but I haven't found where that comes from yet.

It's from here: https://github.com/DFHack/dfhack/blob/f20446534bb7f39425e102bd70daec46e328004f/conf.py#L225

I'm also curious why the page in the screenshot appears to be unstyled; it should look (roughly) the same as https://docs.dfhack.org/en/stable/Contributing.html. Maybe CSS isn't getting bundled properly or something, or whatever browser that is doesn't like serving CSS from the local filesystem?

**Comment by PatrikLundell** [comment] 2020-05-28 18:37
@doloresjane : While it's true I'm not a People Person, I don't think that has anything to do with your reaction. Apparently I've violated some secret code of conduct I'm completely unaware of (hence my response). Would you (or someone else with inside knowledge) please be so kind as to tell me what faux pas I've committed?

As far as I'm concerned the reaction is like getting slapped in the face for telling someone their shoelaces are untied.

**Comment by ab9rf** [comment] 2020-05-29 00:04
I'm reopening this because there does seem to be a real issue here. I've also deleted some of the unnecessary discussion from this issue report.

> I'm also curious why the page in the screenshot appears to be unstyled; it should look (roughly) the same as https://docs.dfhack.org/en/stable/Contributing.html. Maybe CSS isn't getting bundled properly or something, or whatever browser that is doesn't like serving CSS from the local filesystem?

The browser is that screenshot is clearly Edge. However, on my system the CSS works when loaded into Edge, so either that person has their Edge security turned way far up so as to block CSS loads from the local file system, or there's something wrong with either their copy of DFHack or of Edge. Don't think there's anything we can do about that.

**Comment by lethosor** [comment] 2020-05-29 03:31
I was able to reproduce the crash on load; I ran [df-savecheck](https://github.com/lethosor/df-fileutils) on all the `.sav` files and got this:
```
data/save/dfhack-1578/world.sav: chunk 12086 (start=19917936, length=5695): Compression error: unexpected EOF
data/save/dfhack-1578/world.sav: 10354445 bytes unread, 19923635 bytes read
```
so it appears that world.sav is corrupted, although I'm not sure if that happened when it was compressed/uploaded or if the original is also corrupt.

I'm not sure if we want to add `identity_type::None` without investigating the save; `Units::setNickname()` seems to handle unrecognized identity_type values cleanly, but exportlegends would require `None` to also have an `id_tag` attribute, which doesn't really make sense and would probably require some extra adjustments to the script.

**Comment by PatrikLundell** [comment] 2020-05-29 07:42
I suspect it might be possible to get some clues out of the exported legends info set, if the OP would be willing to provide it, as there might be events related to that hist fig indicating what was going on.

**Comment by doloresjane** [comment] 2020-05-29 07:58
[Region Of 13 Divines-00234-10-02-world_history.txt](https://github.com/DFHack/dfhack/files/4700389/Region.Of.13.Divines-00234-10-02-world_history.txt)

**Comment by doloresjane** [comment] 2020-05-29 08:05
http://www.mediafire.com/file/hjs4qcgrq95wnn5/Region_Of_13_Divines-00234-10-02-legends_plus.xml/file

**Comment by PatrikLundell** [comment] 2020-05-29 08:24
The legends_plus file might be useful on its own, but generally the whole set of basic files, typically zipped up, is better. The plus file contains only the additions added by DF, while the "ordinary" file contains the bulk of the history info.
The standard set of files is:
- X-legends.xml
- X-legends_plus.xml
- X-world_history.txt
- X-world_map.bmp
- X-world_sites_and_pops.txt

This set would allow examination using third party tools, such as e.g. Legends Viewer.

**Comment by doloresjane** [comment] 2020-05-29 08:29
https://www.mediafire.com/file/i9b1116t43uyies/Region_Of_13_Divines_-_Copy.zip/file hopefully this save is not corrupted, it works on my end

**Comment by PatrikLundell** [comment] 2020-05-29 08:49
Yes, that save is working, so there's no need for posting the additional exports files.

The curious entry is related to "In the early spring of 234 Ona assumed the identity *Sebeca Coilblocks*" for the character Ona Wealthsexits.

**Comment by doloresjane** [comment] 2020-05-29 08:55
Thanks for helping this is my favorite save game with very interesting people ive found, thanks for being a good help patrik

**Comment by doloresjane** [comment] 2020-05-29 14:57
Giki was a mummy i resurrected

**Closed** 2020-05-31 00:25 UTC
Labels: bug
