### ISSUE TITLE
Dig/Gui Multiple Z Level Stairs Designation Error

### ISSUE THREAD

**Issue by Vactarian** [DFHack/dfhack#2893] opened 2023-02-12 23:03 UTC
![digerror](https://user-images.githubusercontent.com/89357034/218342552-c75f345a-b4d9-49a6-849a-85b355450963.jpg)
When attempting to Designate a Diagonal Stairs going upwards multiple z-levels I keep getting this error.

**Comment by myk002** [comment] 2023-02-12 23:05
@johncosker could you take a look at this?

**Comment by johncosker** [comment] 2023-02-12 23:16
Sure, I won't be able to look at it until tomorrow night, though

**Comment by myk002** [comment] 2023-02-12 23:21
Thanks!

**Comment by johncosker** [comment] 2023-02-12 23:23
@Vactarian does it work okay going down?

**Comment by Vactarian** [comment] 2023-02-13 15:36
@johncosker No, it did once, Now when I try to even go down it does the same error

**Comment by johncosker** [comment] 2023-02-13 22:31
@Vactarian I can't seem to reproduce this, can you upload your save?

A couple things stick out to me, first is the tooltip at the top fo the panel says `1x1x2 (2 tiles)` even though it looks like you have a 3x3 area selected...

Another is the corners of the shape are the purple dots which area supposed to only show up when you mouse over a corner.

@myk002 it looks like the error is on line 767:

`local tile_shape = tile_attrs[tile_type].shape`

`tile_attrs` is coming from `local tile_attrs = df.tiletype.attrs`, so the `tile_type` value is out of bounds, it's coming from 

`local tile_type = dfhack.maps.getTileType(self:get_bounds().x1 + x, self:get_bounds().y1 + y, z)`

This is the check for replacing existing up stairs with up/down. So @Vactarian I'm curious about what tiles are on the top and bottom of where you're trying to place the new stairs.

**Comment by johncosker** [comment] 2023-02-13 23:59
Myk btw the reason I tagged you was because I was wondering if you had any insight into the tile_attrs stuff

**Comment by myk002** [comment] 2023-02-14 00:51
> `tile_attrs` is coming from `local tile_attrs = df.tiletype.attrs`, so the `tile_type` value is out of bounds, it's coming from
> 
> `local tile_type = dfhack.maps.getTileType(self:get_bounds().x1 + x, self:get_bounds().y1 + y, z)`

If the target tile is out of bounds or is in a non-allocated map block, `tile_type` can be `nil`. If the player is drawing a staircase into unallocated territory (and the game only allocates map blocks once they're ready to be exposed), this could be happening.

**Comment by johncosker** [comment] 2023-02-14 01:14
The check should be only happening on the top level of the designation area so I'd be a little surprised if it was not allocated, tomorrow I'll try and reproduce it by trying to dig far down from what's been revealed

**Comment by myk002** [comment] 2023-02-27 05:53
Fixed by https://github.com/DFHack/scripts/pull/619

**Closed by myk002** 2023-02-27 05:53 UTC
