### ISSUE TITLE
"DFHack fatal error: Not a known DF version." on OS X

### ISSUE THREAD

**Issue by acayt** [DFHack/dfhack#576] opened 2015-03-14 04:34 UTC
When I start dfhack by double clicking (which opens in Terminal) on OS X 10.10.2 I get this:
![screen shot 2015-03-14 at 3 27 50 pm](https://cloud.githubusercontent.com/assets/7953937/6650309/4a05b568-ca5f-11e4-9d70-16d40f468f8d.png)

Any idea why this is happening?

**Comment by PeridexisErrant** [comment] 2015-03-14 07:21
What version of DF and DFHack are you using?

I'm not an OSX person, but this looks like version incompatibilities.

**Comment by lethosor** [comment] 2015-03-15 03:38
What is contained in stderr.log? Have you made any modifications to the DF executable?

**Comment by acayt** [comment] 2015-03-15 04:32
2015-03-14 15:58:12.785 dwarfort.exe[845:9668] Warning once: This application, or a library it uses, is using NSQuickDrawView, which has been deprecated. Apps should cease use of QuickDraw and move to Quartz.
Mar 14 15:58:12  dwarfort.exe[845] <Error>: The function ‘CGSFlushWindow’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance. Please use CGSFlushWindowContentRegion instead.
dfhack: saving real SDL functions
dfhack: saved real SDL functions
dfhack: hooking successful
Identifying DF version.
Loading hack/symbols.xml ... OK
Dummy symbol table entry: start_dwarf_count
Loaded 3 DF symbol tables.
Unable to retrieve version information.
File: /Applications/Void/Favourites/Dwarf Fortress/dwarfort.exe
MD5: c6f255222b6f1ca8adcf288af1ad32ed
working dir: /Applications/Void/Favourites/Dwarf Fortress
length:33117332
1KB hexdump follows:


stderr.log above.

Haven't made any modifications that I know of.
Latest DFHack version as well as latest DF version.

**Comment by lethosor** [comment] 2015-03-15 11:01
That md5 doesn't match any of the OS X executables in the 0.40 series, so the executable has probably been modified. You could try redownloading it from http://www.bay12games.com/dwarves/df_40_24_osx.tar.bz2

**Comment by acayt** [comment] 2015-03-15 12:02
Do I have to reinstall the whole game if I redownload that, or just replace the executable?

**Comment by lethosor** [comment] 2015-03-15 12:55
Replacing the executable should work. You could also create a fresh installation and copy over your previous configuration files and saves.

**Comment by acayt** [comment] 2015-03-16 05:13
I can launch DFHack, but "stonesense" won't work. It gives:

 `"[DFHack]# /dfhack: line 15:  3721 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@""`

stderr.log is [here](http://pastebin.com/jBmjQQtq).

**Comment by lethosor** [comment] 2015-03-19 23:31
Neither that nor the contents of stderr.log are particularly helpful, unfortunately (they show that DF crashed and that stonesense was invoked, respectively). Are you using PRINT_MODE:2D? Does it occur with a fresh installation? (No need to delete your current installation - just unpack DF and install DFHack normally.)

**Comment by acayt** [comment] 2015-03-22 01:39
Just tried with fresh installation, and it still happens. If you mean [PRINT_MODE:2D] in my init.txt, [here](http://pastebin.com/5sT64iKb) it is. It appears that I'm using PRINT_MODE:2D but I'm not sure.

**Comment by lethosor** [comment] 2015-03-28 18:05
Could you try replacing SDL_ttf.framework in the libs folder with the one from [here](http://www.libsdl.org/projects/SDL_ttf/release-1.2.html) ([http://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.dmg])?

**Comment by lethosor** [comment] 2015-03-30 21:38
If this still occurs in DFHack r3, can you try launching DFHack with `DFHACK_LOG_MEM_RANGES=1 ./dfhack` and posting the contents of stderr.log somewhere (e.g. Gist)?

**Comment by acayt** [comment] 2015-04-01 22:19
Here's the gist after running dfhack with that command ("DFHACK_LOG", etc). I also replaced the framework with the one you gave me the link to. It still gives the exact error.

**Comment by lethosor** [comment] 2015-04-01 22:26
@danaris perhaps this is an issue with the allegro libraries? Have you encountered this on OS X 10.10?

**Comment by acayt** [comment] 2015-04-01 22:42
@lethosor, is my issue related to #281? It seems to have the same DYLD_INSERT_LIBRARIES error message.

**Comment by lethosor** [comment] 2015-04-01 22:53
"file too short"?

**Comment by acayt** [comment] 2015-04-01 22:56
@lethosor, exactly, I'm not getting that error. Strange though.

**Comment by lethosor** [comment] 2015-04-01 22:57
What error are you getting?

**Comment by acayt** [comment] 2015-04-01 23:00
Same as the picture in my first reply.

[DFHack]# stonesense
Stonesense launched
Using allegro version 5.0.9 r1
[DFHack]# ./dfhack: line 15: 13394 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

**Comment by lethosor** [comment] 2015-04-01 23:11
Oh, the "DYLD_INSERT_LIBRARIES" part is the line in the `dfhack` script where the error occurred (i.e. the line where DF was launched). It's probably not related to #281.
I suppose you could try another print mode (2DSW or 2DASYNC, or possibly TEXT, which would require using `dfhack-run` to run commands), but I suspect the problem is with allegro. I haven't heard of problems with allegro on 10.10, though, which is strange.

**Comment by acayt** [comment] 2015-04-01 23:13
So how would I go about using another print mode?

**Comment by lethosor** [comment] 2015-04-01 23:55
Edit the PRINT_MODE setting in data/init/init.txt (or in a launcher if you're using one).
I can't guarantee that this will work, however. I'll take a look at compiling allegro myself when I get a chance.

**Comment by lethosor** [comment] 2015-05-16 23:26
Can you try copying the allegro libraries from [here](https://www.mediafire.com/?nacwjdazayz9fz7) into hack/libs in your DF folder?

**Comment by lethosor** [comment] 2015-06-12 01:04
I'm going to close this since this is at best a Stonesense issue. If updating allegro to 5.0.11 (see link above) doesn't fix your problem, it would be best to open an issue in the DFHack/stonesense repo instead.

**Closed by lethosor** 2015-06-12 01:04 UTC
Labels: crash

**Comment by SephVelut** [comment] 2015-07-01 04:11
I can confirm stonesense works on 10.10 after replacing the dylibs in hack/lib.
