### ISSUE TITLE
Exportlegends info fails on legends_plus xml

### ISSUE THREAD

**Issue by Castaras** [DFHack/dfhack#1005] opened 2016-10-18 17:47 UTC
DFHack alpha 43.05 64bit. Windows 7 version of Dwarf Fortress. 

The following is printed in the console after typing "exportlegends info" while in the legends mode for a world:

`[DFHack]# exportlegends info`
`    Exporting:  World map/gen info`
`    Exporting:  Legends xml`
`    Exporting:  Extra legends_plus xml`
`...Dwarf Fortress\Dorf 43.05/hack/scripts/exportlegends.lua:184: Cannot invoke f
ield (global).TranslateName(): C++ exception: bad allocation.
stack traceback:`
    `    [C]: in function 'dfhack.TranslateName'`
`...Dwarf Fortress\Dorf 43.05/hack/scripts/exportlegends.lua:184: in glob
al 'export_more_legends_xml'`
` ...Dwarf Fortress\Dorf 43.05/hack/scripts/exportlegends.lua:765: in glob
al 'export_legends_info'`
` ...Dwarf Fortress\Dorf 43.05/hack/scripts/exportlegends.lua:822: in loca
l 'f'`
` D:\Games\Dwarf Fortress\Dorf 43.05\hack\lua\dfhack.lua:562: in function
'dfhack.run_script_with_env'`
`        (...tail calls...)`

Am probably being dense but can't find a log file for dfhack to attach.

**Comment by lethosor** [comment] 2016-10-18 23:04
That's probably enough. Thanks for the report!

I seem to remember TranslateName working, though. It's possible that something broke recently, so I'll check to see if I can reproduce it, but if you have time, it might be helpful to upload the save somewhere.

**Comment by lethosor** [comment] 2016-10-18 23:06
(This could've been a crash so I'll tag it as such.)

**Comment by warmist** [comment] 2016-10-19 05:22
The culprit is here: ` C++ exception: bad allocation`. My guess - out of memory error?

**Comment by lethosor** [comment] 2016-10-19 05:45
That tends to happen when structures are misaligned and someone gets lucky - e.g. a std::string misaligned so that its "length" is 0xffffffff or something impossible to allocate. (Crashes tend to be more common than memory allocation failures, though.)

**Comment by lethosor** [comment] 2016-10-19 05:50
Note: the bad field appears to be the `name` field of at least some `df::abstract_building_*` subclasses. Maybe abstract_building (which doesn't have a name field) changed, since name is at the beginning of a bunch of subclasses. Or it could be an issue with a subclass that does have fields before `name`.

@Castaras I think a save would be helpful here.

**Comment by lethosor** [comment] 2016-10-19 13:50
Should be fixed. Thanks!

**Closed by lethosor** 2016-10-19 13:50 UTC
Labels: bug, crash, develop only, structures

**Comment by Dwarfiex** [comment] 2019-05-31 00:42
> Note: the bad field appears to be the `name` field of at least some `df::abstract_building_*` subclasses. Maybe abstract_building (which doesn't have a name field) changed, since name is at the beginning of a bunch of subclasses. Or it could be an issue with a subclass that does have fields before `name`.
> 
> @Castaras I think a save would be helpful here.
> 
> Edit: looks like it's an issue with the base class - some int32_t fields added in 0.42 are actually pointers.

hi im having the same problem andit really frustrates me that i cant know the world im playing at can you please explain the raws that you deleted thank you

**Comment by lethosor** [comment] 2019-05-31 03:13
What DFHack version are you using? (Run `help` if you don't know.)

What error message are you getting?

https://github.com/DFHack/df-structures/commit/81e2cf023422ad6f01061db12586a0589ef6eac5 was the only change I made, but it's a change to the XML files, not a raw change. It requires recompiling DFHack; it's not something you can change manually. But that change was made almost 3 years ago, and included in a release not long after, so I'm not sure what you're looking for.
