### ISSUE TITLE
LaborManager issue

### ISSUE THREAD

**Issue by guska84** [DFHack/dfhack#1166] opened 2017-09-21 15:54 UTC
As requested in the documentation, I'm opening an issue after experienceing a LaborManager pause. 

Vanilla DF 0.43.05-r2 with PyLNP (Automatic Job Assignments, Multilevel View, Other Automation plugins and Performance Tweaks all turned on in the DFHack menu)

LABORMANAGER: Cannot deduce labor for make crafts job (not bone)
LABORMANAGER: Game paused so you can investigate the above message. Use 'labormanager pause-on-error no' to disable autopausing.

**Comment by guska84** [comment] 2017-09-21 15:56
Apologies, look like this is a duplicate of

https://github.com/DFHack/dfhack/issues/1162

I also had a black pearl job suspend due to lack of materials.

**Comment by ab9rf** [comment] 2017-09-22 15:00
Duplicate of #1162.

**Closed by ab9rf** 2017-09-22 15:00 UTC
