### ISSUE TITLE
Files in raw/init.d/ won't run in arena mode

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2039] opened 2022-03-20 09:29 UTC
(also, why is it called init.d?)

**Comment by myk002** [comment] 2022-03-20 19:01
The "init" means "run on initialization" and the ".d" means "directory". On Unix systems, the /etc/init.d directory is where all the system service startup scripts are located.

In general, a directory that ends in ".d" has the semantics of "the files in this directory each have a different owner but anything that is in this directory will get detected and used".

**Comment by wolfboyft** [comment] 2022-03-20 22:36
Okay, makes sense. Also, bug label? Since I don't have the perms.

**Comment by warmist** [comment] 2022-03-29 07:19
same thing #1266

**Comment by lethosor** [comment] 2022-04-07 18:10
Yep. Duplicate of #1266

**Closed by lethosor** 2022-04-07 18:10 UTC
Labels: bug
