### ISSUE TITLE
Stonesense crash

### ISSUE THREAD

**Issue by gregseit** [DFHack/dfhack#1570] opened 2020-05-06 07:53 UTC
Stonesense crashes immediately after being launched on Windows 10, DF 0.47.04, DFHack 0.47.04-r1

[stderr.log](https://github.com/DFHack/dfhack/files/4585416/stderr.log)

**Comment by lethosor** [comment] 2020-05-06 13:31
Duplicate of https://github.com/DFHack/stonesense/issues/68 - the good news is that a fix has been found

**Closed by lethosor** 2020-05-06 13:31 UTC
