### ISSUE TITLE
[0.42.03-alpha1] exportlegends dies writing legends_plus

### ISSUE THREAD

**Issue by shokolatOtobus** [DFHack/dfhack#780] opened 2015-12-27 08:51 UTC
I recently have created a new world in 0.42.03 (surprise!) with the listed DFHack and went immediately to legends mode to export all with DFHack, all was well until it got to the extra data.

The error thrown:
>.../the/path/to/exportlegends.lua:208: Cannot read field vector<creature_raw*>,-1: index out of bounds

Lazy rendition of stack trace:
>export_more_legends_xml > export_legends_info > f *(main?)*> dfhack.lua

Not a damning bug by any means, but I figure a bit more documentation can't hurt.
If there is any more information I can provide, please ask.

**Comment by Kromtec** [comment] 2015-12-30 13:56
Had not seen that there is already an open issue here and posted in bay12 forums with screenshots:
http://www.bay12forums.com/smf/index.php?topic=139553.msg6701086#msg6701086

**Comment by lethosor** [comment] 2015-12-30 17:17
Turns out the problem is that entities don't necessarily have specific races now, like some site governments in a save I tested. I don't know how tools that use these xml files will handle it, but it should be fixed in the next DFHack version.

**Closed by lethosor** 2015-12-30 17:17 UTC
Labels: bug, develop only, structures
