### ISSUE TITLE
Revflood removes tree-chopping designations

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2047] opened 2022-03-24 17:00 UTC

**Comment by myk002** [comment] 2022-03-24 19:26
Does it remove all dig designations, or just trees?

**Comment by wolfboyft** [comment] 2022-03-25 08:28
Channels on the surface too. I believe it's the lit flag, probably.

**Comment by myk002** [comment] 2022-03-29 18:53
I could not reproduce this. I tried designating trees for chopping and surface tiles for channeling. then I ran `revflood`. the channels and trees stayed designated. what am I doing differently?

**Comment by myk002** [comment] 2022-05-09 23:28
Closing as not reproducible -- please reopen if you have a savegame that can reproduce this.

**Closed by myk002** 2022-05-09 23:28 UTC
Labels: bug
