### ISSUE TITLE
[OSX] Stockpile plugin issues

### ISSUE THREAD

**Issue by fricy** [DFHack/dfhack#434] opened 2014-12-05 22:58 UTC
[Reddit thread](http://www.reddit.com/r/dwarffortress/comments/2o611s/new_dfhack_plugin_saveload_stockpile_settings/cmkzdkn) @Ramblurr

1, If the ./stocksettings folder doesn't exist, then invoking the Load command from the GUI consistently crashes the game. Loading from command line behaves correctly.

2, Quality settings are not restored correctly from a preset. Partially fixed by https://github.com/Ramblurr/dfhack/commit/b9a2ecb440f4fd593dd46f575d70dbb3044d9194

Issue: Create any preset with partially selected quality settings (or use the [Automelt preset](http://dffd.wimbli.com/file.php?id=10170)) and try to load it over a few stockpiles. Observe that the [quality is not always restored correctly,](http://i.imgur.com/wrrcNhr.png) success rate is random. When loaded, these incorrectly restored q.settings can only be deactivated by forbidding/permitting the category first, the control is not responsive to space until.
A workaround is to 'preformat' the stockpile by loading the Animal preset first, then the desired setting.

This bugs are only reproducible on OSX, linux and windows not affected. Tested: 10.7.5 and 10.9.3

**Comment by lethosor** [comment] 2015-01-01 18:03
Also, aren't these caused by the changes in #433?

**Comment by PeridexisErrant** [comment] 2015-01-10 20:06
Are these problems still present in DFHack 40.23-r1?  It looks like they were for a beta version and the final plugin fixed these issues.

**Comment by fricy** [comment] 2015-01-10 20:23
There has not been any [commit for the stockpiles plugin](https://github.com/DFHack/dfhack/pull/433) since this discussion, so 2 is still around. The crash is fixed by https://github.com/DFHack/dfhack/pull/463.

**Comment by lethosor** [comment] 2015-01-10 21:48
Can you take a look and see if the second one is fixed as well? I'd be surprised if it's OS X-specific, but if it is, #463 fixed a number of OS X-specific bugs.

**Comment by fricy** [comment] 2015-01-10 21:54
Already did when testing #463. Also: it happens from the command line too, so not a lua error.  
Also tested https://github.com/DFHack/dfhack/issues/205 to confirm that it remains unfixed.

**Comment by lethosor** [comment] 2015-01-10 22:19
There could well be other bugs in the older libstdc++, not just the one that affects Lua errors. To confirm, you reproduced the _second_ part of this issue with the newer library, correct?
> Quality settings are not restored correctly from a preset.

**Comment by lethosor** [comment] 2015-04-18 23:40
@fricy If this still occurs, what is the problem with restoring quality settings? Are settings enabled when they shouldn't be, disabled when they shouldn't be, or both?

**Comment by lethosor** [comment] 2017-05-19 15:37
Part 1 is resolved, and part 2 sounds similar to #1013, so I'm closing this issue in favor of that one.

**Closed by lethosor** 2017-05-19 15:37 UTC
Labels: bug
