### ISSUE TITLE
getplants marks the wrong tile for trees sometimes

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1014] opened 2016-10-31 15:29 UTC
getplants, when asked to mark trees for chopping, will incorrectly mark the center tile of a 3x3 or larger tree. As this tile is unreachable, the tree will never be chopped down.

**Comment by lethosor** [comment] 2016-10-31 17:15
Do you have a save handy with trees this large?

**Comment by ab9rf** [comment] 2016-10-31 23:55
Not at the moment, but I'll get one to you soon; they're easy to get (any embark with highwood will do).

**Comment by ab9rf** [comment] 2016-11-01 00:15
http://dffd.bay12games.com/file.php?id=12537

Issuing a "getplants highwood" will mark the highwood that's about 20 blocks from the embark wagon for cutting, but it will mark the center square, which is not reachable and thus will never lead to anyone cutting it down.

**Comment by quietust** [comment] 2016-11-05 13:15
Getplants was written back for version 0.31, and it was apparently never updated for multi-tile trees - it'll need to be adjusted to read the tree data and [de]select all trunk tiles on the "base" Z-level

**Comment by PatrikLundell** [comment] 2016-11-15 13:47
I'm not sure I agree with quietust (or misunderstand the comment). I've had the issue myself, and the problem is that the tile marked is the one the tree is located on, i.e. the central tile, but not the other ones. Additional logic is needed to determine that the trunk is 3*3 and select one of the surrounding tiles instead, preferably one that's reachable (i.e. not one on the outer side of a cliff, or one by a cliff edge. A corner should work most times).

**Comment by lethosor** [comment] 2016-11-15 13:51
Yeah, so the issue is that getplants hasn't been updated to handle multi-tile trees, like Quietust said.

**Comment by lethosor** [comment] 2017-05-06 04:18
This should be fixed in the next release. Autochop should also use the right tile (thanks for the save there, @ab9rf!).

**Closed by lethosor** 2017-05-06 04:18 UTC
Labels: bug
