### ISSUE TITLE
Military Equip screen issues; DFHack version 0.44.02-alpha1 (release) on x86_64 (linux)

### ISSUE THREAD

**Issue by Caeboox2** [DFHack/dfhack#1199] opened 2017-12-15 17:51 UTC
When cycling through squad members the equipment list disappears. Without DFHack running this works properly.

**Comment by lethosor** [comment] 2017-12-15 19:14
Can you clarify? What tab are you in? I'm not very familiar with this screen, so I can't spot anything wrong after poking around some.

**Comment by Caeboox2** [comment] 2017-12-15 21:58
Within default game interface pressing `m` for military, then `e` for equip, then cursor right into the soldier list. Now, when I cursor up or down to change the selected soldier, the far right list disappears.
(I guess a problem with DFHack's search feature)

I had this issue with an imported save from 43.05, I'm generating a new world right now and check it again. Will try to provide a screenshot as well.

Also, my only changes to vanilla are a square tileset.

**Comment by ildabaoth** [comment] 2017-12-17 21:18
Hi. This is also happening to me with the windows x64 version. I also think it's an issue with the DFHack's search, because as soon as q is pressed (the hotkey for search) and anything is typed, the full selection list disappears.

**Comment by lethosor** [comment] 2017-12-17 22:51
Okay, I'm not seeing anything from the search plugin at all on this screen. Upon further investigation, the search plugin is only supposed to be enabled in the "positions" tab, probably for exactly this reason, but the screen (viewscreen_layer_militaryst) is misaligned, so the "page" field is not right. I'm guessing it's managing to read "0" from that field and interpreting that as the "positions" tab for both of you, and displaying the search option.

**Comment by quietust** [comment] 2017-12-18 00:08
Should be fixed with DFHack/df-structures@e536d27

**Comment by ildabaoth** [comment] 2017-12-18 14:29
Thanks, guys. I'm unfamiliar about how to update DFHack on windows and I don't run DF on the linux computer, so I'll wait for a LNP update. Cheers. :)

**Comment by lethosor** [comment] 2017-12-18 20:15
Yeah, the search option is showing up in the right place for me now, and seems to be working. I'm assuming that means this issue is fixed too, although I wasn't able to reproduce it in the first place. I'll close it, but let me know if it continues in the next DFHack release.

**Closed by lethosor** 2017-12-18 20:15 UTC
Labels: bug, structures
