### ISSUE TITLE
Segmentation fault when building Soap Maker's workshop with labormanager enabled

### ISSUE THREAD

**Issue by gaetjen** [DFHack/dfhack#1039] opened 2016-12-11 12:22 UTC
Unpausing the game with labormanager enabled and a soap maker's workshop designated to be built results in Segmentation fault and DF crash. Alternatively, queuing up a soap maker's workshop and enabling labormanager crashes. autolabor seems to be working though.
@ab9rf

**Comment by ab9rf** [comment] 2016-12-11 20:09
Which version of DF, and on what platform?

I build soapmaker's workshops all the time without any trouble, but I haven't tested with 43.05 yet.

**Comment by ab9rf** [comment] 2016-12-11 21:49
Soap maker is a custom workshop. Do you also get a crash when you build an screw press (the only other custom workshop in stock DF)? If so, then the problem is probably in the structure definitions for df::building_defst.  If not, then I have no idea why it would work for one but not the other.

**Comment by lethosor** [comment] 2016-12-11 22:02
Also, are you using the 32-bit or 64-bit build of DF?
If it's 64-bit OS X or Linux, then this is the most likely cause, and we'll do another release (since it was fixed less than 2 weeks ago): https://github.com/DFHack/df-structures/commit/5fba660359999c0e670daa928858e4b4ffbe85a4

**Comment by ab9rf** [comment] 2016-12-11 22:42
Cannot confirm this bug with 43.05 and develop HEAD on win64. I genned a fresh pocket world, embarked in a fairly ordinary location, making sure the consist included a bucket, a block, and a barrel, and immediately after arriving enabled labormanager and told the dorfs to build a soapmaker's workshop. Went fine.

Either this is specific to linux or the problem has already been fixed.

**Comment by lethosor** [comment] 2016-12-11 22:45
sizeof(long) == sizeof(int) in both Windows builds.

**Comment by gaetjen** [comment] 2016-12-12 12:23
DFHack version 0.43.05-alpha2 (release) on x86_64 Linux from the releases page.

Also crashes when building a screw press.

**Comment by lethosor** [comment] 2016-12-12 14:39
Yeah, it's probably the building_def layout issue that got fixed. If you want to double-check, run `:lua ~df.global.world.raws.buildings.all[0]`, and it should crash after build_labors (and stuff after `build_key`) won't make sense).

**Comment by lethosor** [comment] 2016-12-28 04:37
I'm assuming this was fixed in alpha3. Feel free to reopen this if it persists in alpha3 or any newer versions, though.

**Closed by lethosor** 2016-12-28 04:37 UTC
Labels: crash, structures
