### ISSUE TITLE
Quicksave hotkey doesn't work from example init

### ISSUE THREAD

**Issue by Davidj361** [DFHack/dfhack#588] opened 2015-03-27 11:24 UTC
I utilized your example dfhack.ini file. I noticed that when I tried activating the quicksave hotkey which was this
`keybinding add Ctrl-Shift-S@dwarfmode/Default quicksave`
it did not activate. But I managed to get it working with adding quotations as so
`keybinding add Ctrl-Shift-S@dwarfmode/Default "quicksave"`

I'm not sure if this is a bug or if your example ini file needs to be updated.

**Comment by lethosor** [comment] 2015-03-27 15:09
Quotes shouldn't make a difference unless the command has spaces in it. Are you using quickfort?

**Comment by Davidj361** [comment] 2015-03-27 20:55
I did but I closed it to double check if it was causing issues.

**Comment by lethosor** [comment] 2015-03-28 18:14
What do `keybinding list` and `keybinding add Ctrl-Shift-S@dwarfmode/Default` display?

**Comment by expwnent** [comment] 2015-03-29 17:02
For me ``keybinding list Ctrl-Shift-S@dwarfmode/Default`` yields "No bindings." I have the same problem with the quicksave shortcut.

**Comment by expwnent** [comment] 2015-03-29 17:08
I have the same problem. ``keybinding list`` doesn't print all bindings. ``keybinding list Ctrl-Alt-S@dwarfmode/Default`` prints "No bindings." even after manually typing ``keybinding add Ctrl-Alt-S@dwarfmode/Default quicksave``.

Tested on Windows. It works with ``Ctrl-Shift-S``, but keybinding list still fails even then.

**Comment by Davidj361** [comment] 2015-03-29 17:57
```
[DFHack]# keybinding list
Usage:
  keybinding list <key>
  keybinding clear <key>[@context]...
  keybinding set <key>[@context] "cmdline" "cmdline"...
  keybinding add <key>[@context] "cmdline" "cmdline"...
Later adds, and earlier items within one command have priority.
Supported keys: [Ctrl-][Alt-][Shift-](A-Z, or F1-F9, or Enter).
Context may be used to limit the scope of the binding, by
requiring the current context to have a certain prefix.
Current UI context is: dwarfmode/Default
[DFHack]# keybinding list Ctrl-Shift-S@dwarfmode/Default
No bindings.
```

Which is weird since pressing Ctrl-Shift-S does quicksave for me.

**Comment by lethosor** [comment] 2015-03-29 19:37
@expwnent 
>``keybinding list Ctrl-Alt-S@dwarfmode/Default`` prints "No bindings." even after manually typing ``keybinding add Ctrl-Alt-S@dwarfmode/Default quicksave``.

What about `keybinding list Ctrl-Alt-S`? That works for me on OS X, but including the context doesn't.

**Comment by Davidj361** [comment] 2015-03-29 23:01
`[DFHack]# keybinding list Ctrl-Alt-S
No bindings.`

**Comment by lethosor** [comment] 2015-03-30 01:44
Did you bind quicksave to that key? Check stderr.log to see if keybinding was invoked for that command.

**Comment by Davidj361** [comment] 2015-03-30 02:29
No I rebounded it like I said in the OP.
`keybinding add Ctrl-Shift-S@dwarfmode/Default "quicksave"`

**Comment by lethosor** [comment] 2015-03-30 02:32
Well, does that show up in the keybinding list? (With and/or without the context)

**Comment by Davidj361** [comment] 2015-03-31 01:45
`[DFHack]# keybinding list
Usage:
  keybinding list <key>
  keybinding clear <key>[@context]...
  keybinding set <key>[@context] "cmdline" "cmdline"...
  keybinding add <key>[@context] "cmdline" "cmdline"...
Later adds, and earlier items within one command have priority.
Supported keys: [Ctrl-][Alt-][Shift-](A-Z, or F1-F9, or Enter).
Context may be used to limit the scope of the binding, by
requiring the current context to have a certain prefix.
Current UI context is: dwarfmode/Default
[DFHack]# keybinding list Ctrl-Shift-S@dwarfmode/Default
No bindings.`

![screenshot](https://i.imgur.com/TobhAkb.png)

**Comment by lethosor** [comment] 2015-03-31 01:48
Try `keybinding list Ctrl-Shift-S`
(By "context" I meant "@dwarfmode/Default")

**Comment by Davidj361** [comment] 2015-03-31 14:50
Yes it works, it doesn't work if I don't use quotes (")
`[DFHack]# keybinding list Ctrl-Shift-S
  @dwarfmode/Default: quicksave`

**Comment by lethosor** [comment] 2015-04-18 23:37
I haven't been able to reproduce this. Is Ctrl-Shift-S the only keybinding using Ctrl-Shift that doesn't work? Is this platform-specific?

**Comment by lethosor** [comment] 2015-08-09 17:18
I still can't reproduce this. Quotes are stripped out before the `keybinding` command is invoked, so it's highly unlikely that they're causing the issue. @expwnent I did fix a few issues with keybindings on the `develop` branch recently, so can you see if this still occurs?

**Comment by lethosor** [comment] 2015-11-08 03:35
I'm going to assume that this was fixed by keybinding- and init-related changes, but let me know if this is still an issue in r4.

**Closed by lethosor** 2015-11-08 03:35 UTC
Labels: bug
