### ISSUE TITLE
Stonesense Crashes on window Resize

### ISSUE THREAD

**Issue by ChiefCurtains** [DFHack/dfhack#2627] opened 2023-01-17 13:50 UTC
When resizing, maximizing or minimizing the Stonesense viewer, the game occasionally crashes.

I have been unable to find a log output for the crash but it seems to be exclusive to resizing the window and is inconsistent. Sometimes it will crash, sometimes it will resize fine. 

To reproduce it, simply run Stonesense with DF either maximized or Fullscreen and attempt to resize the Stonesense window.

**Comment by lethosor** [comment] 2023-01-18 03:27
We have a separate issue tracker for Stonesense, and this sounds like a duplicate of https://github.com/DFHack/stonesense/issues/38 to me (but thanks for the report!)

**Closed by lethosor** 2023-01-18 03:27 UTC
