### ISSUE TITLE
Not a known DF version

### ISSUE THREAD

**Issue by Ray6661** [DFHack/dfhack#2861] opened 2023-02-10 15:05 UTC
I had DF hack running fine, but I tried to start it the next day and it will not start, I have tried uninstalling DF four times with a fresh install and DF hack and it still never boots up even with the latest hack version.

When I check stderr it gives me this

> DFHack build: 50.05-alpha3.1-0-g71deeb7a
> Starting with working directory: D:\SteamLibrary\steamapps\common\Dwarf Fortress
> Identifying DF version.
> Loading hack\symbols.xml ... OK
> v0.50.05-steam SDL win64 (windows): PE: 0x63B6063B
> v0.50.04-steam SDL win64 (windows): PE: 0x63a2a9ad
> Loaded 2 DF symbol tables.
> Unable to retrieve version information.
> PE timestamp: 0x63e29e0c
> Not a known DF version.
> DFHack will now deactivate.

Please help my 50 z level gem node will not mine its self, and I need df hack to fix a water problem.

**Comment by lethosor** [comment] 2023-02-10 15:06
Duplicate of #2841, #2838, #2839

**Closed by lethosor** 2023-02-10 15:06 UTC
