### ISSUE TITLE
DFHack outdated

### ISSUE THREAD

**Issue by TheGifler** [DFHack/dfhack#2839] opened 2023-02-07 17:59 UTC
DFhack is outdated for current version of DF.
[stderr.log](https://github.com/DFHack/dfhack/files/10678077/stderr.log)

**Comment by Stealthii** [comment] 2023-02-07 18:34
Duplicate of #2838

**Comment by lethosor** [comment] 2023-02-07 19:51
This has and always will be the case. DFHack requires information about the DF executable that can only be obtained after DF has been built, so it is impossible (without time travel) for a DFHack release from the past to support a DF release from the future.

See also: https://docs.dfhack.org/en/stable/docs/Installing.html#requirements

> DFHack releases generally only support the version of Dwarf Fortress that they are named after. For example, DFHack 0.40.24-r5 only supported DF 0.40.24. DFHack releases _never_ support newer versions of DF, because DFHack requires data about DF that is only possible to obtain after DF has been released.

**Closed by lethosor** 2023-02-07 19:51 UTC
