### ISSUE TITLE
Quickfort unable to designate Tracks on excavated ramps

### ISSUE THREAD

**Issue by johnabsher** [DFHack/dfhack#2004] opened 2022-02-03 21:27 UTC
You are unable to designate tracks on upwards or downwards slopes. Some testing:

The blueprint :
```
#dig
T(1x2),#
      ,#
```
When run on a single 2-tile stretch w/ a stone floor to the south and an upwards ramp to the north
```
|^|
| |
```

gives me
```
|^|
|↑|
```
With just a single tile track pointing north on the southern tile, and no change to the northern one. I would have expected something like 
```
|⇩|
|↑|
```
With a N track on the bottom, and a S Ramp on top.

**Comment by myk002** [comment] 2022-02-04 01:49
Designating ramps on upwards slopes should work, but I expect nothing to happen for downwards slopes. The base game doesn't designate anything for downwards slopes either (IIRC). I'll try to reproduce this issue tomorrow, but just to check, the upwards slope in your example was a hard material, right?

Until I get this fixed, you can probably use single-tile track designations to work around the issue. E.g.:
```
#dig
trackrampS
trackN
```

**Comment by johnabsher** [comment] 2022-02-04 02:26
Yep  - hard stone channeled from the layer above

**Comment by myk002** [comment] 2022-02-04 18:50
I was unable to reproduce this in my fort.  I similarly had an excavated ramp and applied the following blueprint (`track.csv`) with the cursor on a ramp (that is, an upward slope) with a floor tile to the south:
```
#dig
T(1x2)
```
I ran the following command and got the output:
```
[DFHack]# quickfort run -v track.csv
applying spreadsheet cell A2 with text "T(1x2)" to map coordinates (55, 46, 117)
setting priority to 4
setting priority to 4
run track.csv -n  successfully completed
  Tiles designated for digging: 2
```
Which is what I expected, and on the map I see a trackrampS and a trackN, also as expected.

Could you upload your savegame somewhere so I can see what is different about your setup?

**Comment by myk002** [comment] 2022-02-07 22:45
Thank you for the video and savegame -- it made the problem quickly clear to me. The issue is that there *was* a bug here, but I have [fixed it](https://github.com/DFHack/scripts/commit/ae8809f1b87b3471b3334e89d2cfb4e90c69855f) since the latest official release. I just happen to have done a good amount of work on tracks recently.

You can pick up a recent dev build from https://dfhack.org/builds/ (click on the build badge under "Unstable automated builds" and download the build for OSX) or [compile it yourself](https://docs.dfhack.org/en/stable/docs/Compile.html)

It is possible that just updating the quickfort script itself will work. I don't *think* I depend on any recent DFHack core changes, but it's been a while since the last release and I'm not completely sure. You can try this first, though, and see if it works for you.

- Download the `quickfort.lua` file and everything in `internal/quickfort` from the https://github.com/DFHack/scripts repo.
- Overwrite the corresponding files in your df directory under `hack/scripts/`
- Then retry running the track blueprint.

I'm going to close this bug report, since the issue has technically been fixed. Please feel free to continue this discussion on the [forums](http://www.bay12forums.com/smf/index.php?topic=176889.375) if you have any followup questions.

**Closed by myk002** 2022-02-07 22:45 UTC
