### ISSUE TITLE
building permanently suspended when placed

### ISSUE THREAD

**Issue by G48sddsdsdsd** [DFHack/dfhack#3580] opened 2023-07-18 17:12 UTC
can't press on resume, only cancel, and every time i place a building it automatically goes into suspend mode and nobody starts putting materials to build it. this happens to everything. workshops, wells, and walls
[autosave 2.zip](https://github.com/DFHack/dfhack/files/12083966/autosave.2.zip)
i just changed computers so this is a fresh install and these are the mods(i started a world without mods and it happened anyways):
[mods.zip](https://github.com/DFHack/dfhack/files/12083980/mods.zip)
![image](https://github.com/DFHack/dfhack/assets/139907184/de389159-7fe6-4238-a1d1-4394f4a2b00d)

**Comment by G48sddsdsdsd** [comment] 2023-07-18 17:14
sometimes the buildings also just dissapear when suspended too long

**Comment by ab9rf** [comment] 2023-07-18 20:21
have you ever used Dwarf Therapist?

**Comment by myk002** [comment] 2023-07-18 20:27
To clarify the above, DT adds a config file that is saved with DFHack and can cause this behaviour. If you go into the labor screen and there's a warning there that says DT is in control, then this is what the problem is.

**Comment by myk002** [comment] 2023-09-02 02:11
Looking at the save, this is a fresh embark with no building materials available. Closing as working as intended

**Closed by myk002** 2023-09-02 02:11 UTC
