### ISSUE TITLE
feature request: quickfort: allow x,y,z placement offsets in meta blueprints

### ISSUE THREAD

**Issue by klenze** [DFHack/dfhack#1998] opened 2022-01-10 02:05 UTC
For some types of blueprints (pump stacks, spiral train tracks), it would be helpful to apply blueprints in meta mode with a configurable offset. 
z offsets can technically be specified, but only as increments and decrements. 

Assuming I have painstakingly defined eight levels of a 3x3 spiral track, I could them do (using fantasy `offset` syntax)
```
#meta label(spiral32)
/spiral offset(0;0;0)
/spiral offset(0;0;8)
/spiral offset(0;0;16)
/spiral offset(0;0;24)
```

In a similar vein, bedrooms could be defined once as a prototype and then instantiated repeatedly, allowing the user to easily update their design.

I do not think that such a feature would necessarily lead to range loop expressions in meta blueprints, then parametric blueprints and eventually Turing-complete blueprints. (-:

**Comment by myk002** [comment] 2022-01-10 04:41
This looks doable, and the general syntax looks like it should be forward compatible with other potential features like rotation and repetition (and Turing completeness).

Are z offsets necessary? Meta blueprints already have `#<` and `#>` for going up and down z-levels. For example, the [Dreamfort apartments meta blueprint](https://docs.google.com/spreadsheets/d/1QNHORq6YmYfuVVMP5yGAFCQluary_JbgZ-UXACqKs9g/edit?usp=drivesdk). How about just `offset(X;Y)`?

I think I'm happy with `offset` as the keyword. `translate` might be more technically accurate, but `translate` is longer than `offset` and some people might not be aware of the mathematical meaning of the term `translate`.

To make sure I understand what is being asked for here, could you give me a blueprint for `/spiral` and a reference blueprint for how you expect it to be applied to the map? I can then use those blueprints directly in quickfort's automated regression tests.

**Comment by klenze** [comment] 2022-01-12 00:26
> Are z offsets necessary? Meta blueprints already have `#<` and `#>` for going up and down z-levels. For example, the [Dreamfort apartments meta blueprint](https://docs.google.com/spreadsheets/d/1QNHORq6YmYfuVVMP5yGAFCQluary_JbgZ-UXACqKs9g/edit?usp=drivesdk). How about just `offset(X;Y)`?
> 
This would make my above meta a bit longer:

```
#meta label(spiral32)
/spiral
#>
#>
#>
#>
#>
#>
#>
#>
/spiral
#>
#>
#>
#>
#>
#>
#>
#>
/spiral
#>
#>
#>
#>
#>
#>
#>
#>
/spiral
``` 
This is because apparently, level changes in blueprints called by meta (henceforth, "called blueprint", CBP) are not propagated back to the meta blueprint. Like passing a copy of some variable `z_pos` to the called blueprints, who can do with it whatever they wish. I feel this is reasonable, the contents of one CBP should not affect the placement of another CBP. 

I don't have df right now, but by spiral, I meant something like
```
#dig label(spiral)
h, , ,#
 , , ,#
 , , ,#
#>
 ,h, ,#
 , , ,#
 , , ,#
#>
 , ,h,#
 , , ,#
 , , ,#
#>
 , , ,#
 , ,h,#
 , , ,#
#>
 , , ,#
 , , ,#
 , ,h,#
#>
 , , ,#
 , , ,#
,h, ,#
#>
 , , ,#
 , , ,#
h, , ,#
#>
 , , ,#
h, , ,#
 , , ,#
#
```
spiral32 is meant to be the equivalent to pasting the spiral blueprint four times (replacing all but the last hashes in the first column with #>).

Alternatively to z offsets, a way to change the current z level by n (e.g. += instead of just increment & decrement) would also be fine for my purposes. Given that DF is not likely to allow arbitrary directions of gravity (a la Manifold Garden) any time soon, it is reasonable to treat the z axis different from the others. (Same story for rotations: most bedrooms are not terribly useful when rotated around the x or y axis).

**Comment by myk002** [comment] 2022-01-12 00:53
I see. I think this use case might be better handled by a "repeat" keyword rather than an "offset" keyword. For example:
```
#meta dig four spirals down
/spiral repeat(down 4)
```
Which would detect how many z-levels the blueprint spans and automatically jump down that far to start the next iteration.

`offset` is still useful, but would be more verbose and error prone for this kind of blueprint, don't you think?

**Comment by myk002** [comment] 2022-02-09 02:38
I have `repeat` implemented for meta blueprints, just needs some code cleanup and regression tests and I'll merge.

That should meet the immediate requirements of this feature request, but there are a few more tasks before I can fully close this out:
- documentation in the blueprint guide
- command line access (I'm thinking `--repeat direction,num`)
- command line documentation
- update Dreamfort blueprints to use the feature (the central staircase and the six levels of apartment housing)

Also, I'll finally be able to merge pump stack blueprints into the blueprint library. I've had them written for a while now, but they were ugly and difficult to use without the ability to repeat the blueprint a configurable number of times.

**Comment by myk002** [comment] 2022-02-12 21:23
Here are the draft docs for the blueprint guide (in the "Meta blueprints" section):

<section id="meta-blueprints"><section id="meta-markers"><h4 style="font-family: Georgia, serif; font-weight: normal; margin: 30px 0px 10px; padding: 0px; font-size: 22.1px;">Meta markers<a class="headerlink" href="#meta-markers" title="Permalink to this headline" style="color: rgb(221, 221, 221); text-decoration: none; visibility: hidden; padding: 0px 4px;"></a></h4><p style="hyphens: manual; line-height: 1.4em;">You can tag referenced blueprints with markers to modify how they are applied. These markers are similar to<span> </span><a class="reference internal" href="#modeline-markers" style="color: rgb(0, 75, 107); text-decoration: none; border-bottom: 1px dotted rgb(0, 75, 107);">Modeline markers</a>, but are only usable in meta blueprints. Here’s a quick list of examples, with more details below:</p>

Example | Description
-- | --
repeat(down 10) | Repeats a blueprint down z-levels 10 times

<p style="hyphens: manual; line-height: 1.4em;"><strong>Repeating blueprints</strong></p><p style="hyphens: manual; line-height: 1.4em;">Syntax: repeat(&lt;direction&gt;[, ]&lt;number&gt;)</p><p style="hyphens: manual; line-height: 1.4em;">The direction can be<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">up</span></code><span> </span>or<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">down</span></code>, and the repetition works even for blueprints that are themselves multi-level. For example:</p><div class="highlight-dfhack notranslate" style="clear: both; margin: 1em 0px;"><div class="highlight" style="background: rgb(255, 255, 255);"><pre style="line-height: 1.3em; overflow: auto hidden; clear: both; font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background: rgb(238, 238, 238); padding: 7px 30px; margin: 0px;"><span></span><span class="c1" style="color: rgb(64, 128, 144); font-style: italic;">#meta label(2beds) dig 2 levels of bedrooms</span>
dig_bedrooms/1 repeat(down 2)

<span class="c1" style="color: rgb(64, 128, 144); font-style: italic;">#meta label(6beds) dig 6 levels of bedrooms</span>
/2beds repeat(down 3)
</pre></div></div><p style="hyphens: manual; line-height: 1.4em;">You can use<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">&lt;</span></code><span> </span>and<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">&gt;</span></code><span> </span>for short, instead of<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">up</span></code><span> </span>and<span> </span><code class="docutils literal notranslate" style="font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background-color: rgb(236, 240, 243); color: rgb(34, 34, 34);"><span class="pre" style="hyphens: none; overflow-wrap: break-word;">down</span></code>. The comma or space between the direction and the number is optional as well. The following lines are all equivalent:</p><div class="highlight-dfhack notranslate" style="clear: both; margin: 1em 0px;"><div class="highlight" style="background: rgb(255, 255, 255);"><pre style="line-height: 1.3em; overflow: auto hidden; clear: both; font-family: Consolas, Menlo, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, monospace; font-size: 0.9em; background: rgb(238, 238, 238); padding: 7px 30px; margin: 0px;"><span></span>/2beds repeat(down 3)
/2beds repeat(down, 3)
/2beds repeat(&gt;3)
</pre></div></div></section></section>


And here are the draft docs for the commandline:

`-r`, `--repeat <direction>[,]<num levels>`
    Repeats the specified blueprint(s) up or down the requested number of
    z-levels. Direction can be `up` or `down`, and can be abbreviated with
    `<` or `>`. For example, the following options are equivalent:
    `--repeat down,5`, `-rdown5`, and `-r>5`.


Does this look clear to you?

**Comment by myk002** [comment] 2022-02-16 16:41
As I just posted to the [forums](http://www.bay12forums.com/smf/index.php?topic=176889.msg8352871#msg8352871), `repeat` looks lonely without peers, so I'm implementing `transform` and `shift` as part of this FR as well. Data structure and algorithm design work is done, docs are done for the commandline but not yet for meta blueprints in the blueprint guide. implementation/testing is in progress

**Comment by myk002** [comment] 2022-02-18 22:20
I did not end up including z-shifts. I implemented it, but I found that it made the `repeat` logic much more complicated, so I backed it out. I think z-shifts should be covered by the new `#>number` syntax, but we can revisit this if that syntax proves to be inadequate.

**Comment by myk002** [comment] 2022-02-18 23:54
Almost done here. I've updated the [Dreamfort blueprints](https://drive.google.com/drive/folders/1iS90EEVqUkxTeZiiukVj1pLloZqabKuP) online, but I haven't tested the changes yet. I'll postpone integrating transformations into the `gui/quickfort` script until I implement interactive previews. The current interface isn't well suited to managing the transformation options. The screen I have planned for previews will be able to manage it much better.

**Closed** 2022-02-20 01:54 UTC
