### ISSUE TITLE
crash on travel in adventure mode

### ISSUE THREAD

**Issue by thatonezoey** [DFHack/dfhack#816] opened 2016-02-07 16:18 UTC
i dont know why, all i know is it happens with dfhack enabled and does not when its disabled.

**Comment by lethosor** [comment] 2016-02-07 16:26
Are you using TwbT? Can you try disabling specific DFHack tools to see what the problem is?
If not, please upload/attach a save and provide instructions for reproducing the issue.

**Comment by thatonezoey** [comment] 2016-02-07 17:20
as far as i can tell it is twbt but i have no clue why.
and i cant include the save file, even compressed its to big.
and to reproduce it, from anywhere, fast travel (T) move one space, (UNLOADING ZONE), crash.

do you know why twbt would cause a crash like that? i suppose i could just play without it but it make everything so much nicer.

**Comment by maxthyme** [comment] 2016-02-08 10:33
Old bug with twbt and travel mode. If you notice it is most common when you are moving from the smaller near-site map to the wide view wilderness travel map.

**Comment by lethosor** [comment] 2018-05-17 02:14
Closing since this was probably TWBT, but feel free to reopen this if it's still an issue without TWBT.

**Closed by lethosor** 2018-05-17 02:14 UTC
Labels: crash
