### ISSUE TITLE
startdwarf errors out

### ISSUE THREAD

**Issue by jobywalker** [DFHack/dfhack#819] opened 2016-02-11 15:46 UTC
I tried using startdwarf for the first time the result:

> [DFHack]# startdwarf 14
E: RuntimeError: ./hack/scripts/startdwarf.rb:18: patch address not available
 ./hack/scripts/startdwarf.rb:18
 (eval):19:in 'load'
 (eval):19
 (eval):19:in 'catch'
 (eval):19

DFHack version 0.42.04-alpha2 (release) + TWBT 5.55

**Comment by lethosor** [comment] 2016-02-17 06:31
Duplicate of DFHack/df-structures#79

**Closed by lethosor** 2016-02-17 06:31 UTC
