### ISSUE TITLE
workflow plugin: repeating jobs cause segfault

### ISSUE THREAD

**Issue by melkor217** [DFHack/dfhack#771] opened 2015-12-18 20:50 UTC
How to reproduce:

- enable workflow plugin
- set any workshop job to repeat
- unpause

I was using:
df_42_02_linux
dfhack from dev branch (8a347db6157d62e22737e512f7b9fb32c8285ba2)

**Comment by lethosor** [comment] 2015-12-18 21:32
This might be fixed in the most recent df-structures commit - can you check that out in library/xml and recompile?

**Comment by melkor217** [comment] 2015-12-18 22:51
dfhack build fails with df-structures HEAD (f3ae4d4fb31301e95a147539e407d0c636ee7d15)
https://gist.github.com/melkor217/d6ded8b13d7dfb6cc12d
It looks like df::reaction_product::produce call should be fixed at library/modules/Items.cpp:1376

**Comment by lethosor** [comment] 2015-12-18 23:46
That's fixed now. I can't reproduce the problem from the steps you gave, although I didn't check before. Can you see if it works for you now?

**Comment by melkor217** [comment] 2015-12-19 00:18
Yaay, it works now. Thanks a lot!

**Closed** 2015-12-19 00:18 UTC
Labels: develop only

**Comment by melkor217** [comment] 2015-12-19 05:57
By the way, stockflow appears to work too.

**Comment by lethosor** [comment] 2015-12-19 14:12
Yeah, Eswald fixed that in #770, which should be merged shortly.
