### ISSUE TITLE
Crash to desktop on Search in the Unit view

### ISSUE THREAD

**Issue by OzoneGrif** [DFHack/dfhack#928] opened 2016-05-18 01:38 UTC
I managed to reproduce that bug a few times easily.
This is DFHack 0.42.06-r1 (from LNP)

- Go to the UNITS view (U)
- Go to the OTHERS tab (I'm not sure how mandatory this is)
- Hit (Q) to Search and then enough letters so the unit list becomes empty
- Hit the arrow keys while the cursor is still editing the search field (left/right/up/down)
- Crash to desktop

The expected behavior was to switch between the unit list's tabs.

Thanks for the amazing work <3

**Comment by lethosor** [comment] 2016-05-18 01:51
Which arrow keys? Left/right or up/down?

**Comment by lethosor** [comment] 2016-05-18 02:03
Okay, I got it to reproduce:
- Select a tab with units
- Enter a search query that doesn't match any units
- Press `up`, then `left`

The traceback appears to be in DF.

**Comment by lethosor** [comment] 2016-05-18 02:07
`cursor_pos[n]` is getting set to -1 somehow (which is bad)

**Comment by lethosor** [comment] 2016-05-18 02:18
DF can handle a cursor_pos of -1, but only if the list is empty. I think we restore the list right before switching tabs, at which point DF panics because cursor_pos is still -1 but the list isn't empty anymore (or something like that). Anyway, saving and restoring the cursor position ought to work.

**Comment by lethosor** [comment] 2016-05-18 03:26
Fixed in the next release.

**Closed by lethosor** 2016-05-18 03:26 UTC
Labels: bug, crash, search
