### ISSUE TITLE
Scroll missing after uncollapsing bin in trade depot

### ISSUE THREAD

**Issue by Franzyd** [DFHack/dfhack#3111] opened 2023-03-27 08:39 UTC
In the trade depot screen I collapsed all bins, then manually uncollapsed one export bin. The scrollbar went missing and I couldn't scroll at all through the export items. I collapsed everything, then manually uncollapsed the bin category and the export bin and the scroll was working again. Sometime during that an error was logged:

![image](https://user-images.githubusercontent.com/56082757/227887333-a24d9dd3-8fe5-414a-b5bb-c9f9df10ab7d.png)

**Comment by myk002** [comment] 2023-03-27 08:46
could you upload your savegame and mods and add a link to them here? I might have trouble reproducing this without your specific setup

**Comment by Franzyd** [comment] 2023-03-27 09:00
Sure, [here's the save](https://drive.google.com/file/d/1rg7BtgWNDkn6nrToF5n6lIi4D7m6g2uL/view?usp=sharing), no mods used. I traded my Gem bin (apricot wood) with the elven caravan.

**Comment by myk002** [comment] 2023-03-27 09:28
Thanks! I'll check it out

**Comment by myk002** [comment] 2023-03-27 10:59
it looks like that zip file doesn't include all the save files -- there's no world.dat or world.save file, for example.

**Comment by Franzyd** [comment] 2023-03-27 11:07
I zipped the whole autosave folder so I think I got everything. The save is compressed if it matters

**Comment by myk002** [comment] 2023-03-27 11:15
Got it. I was using an older utility to decompress and got "130 files skipped because of unsupported compression or encoding."

using 7z to decompress got it all. sorry for the noise!

**Comment by myk002** [comment] 2023-03-27 11:23
loaded the save, but there aren't any merchants at the trade depot. Do you happen to have a save where the bug can be reproduced?

**Comment by Franzyd** [comment] 2023-03-27 11:49
[Here](https://drive.google.com/file/d/1fSDjOU0xv8UY5BOVbvQGfXSlElKEJLQ9/view?usp=sharing)'s a save with elves and the bin in the depot, this time zipped with a more common compression method.

I can't recreate the scrollbar disappearing, but I do notice that the selecting items inside bin and collapsing bin scripts throw errors, with Shift click showing the log in my first comment and Ctrl click showing a similar one:
![image](https://user-images.githubusercontent.com/56082757/227931773-064f64bc-efc9-412d-b8b1-0b13e5a18b34.png)
Also when ctrl clicking the bin a second time it gives an error on line 83 instead, further clicks work ok.
This time the only error I see is the scrollbar **not** disappearing when the bin has been collapsed.

**Comment by myk002** [comment] 2023-03-27 15:45
repro'd. thanks!

**Comment by myk002** [comment] 2023-03-27 19:49
this one turned out to be an interesting challenge. fixed now. Thanks for the help!

**Closed** 2023-03-27 20:53 UTC
