### ISSUE TITLE
[0.44.12-r2-OSX] dyld: could not load inserted library './hack/libdfhack.dylib'

### ISSUE THREAD

**Issue by linonetwo** [DFHack/dfhack#1451] opened 2019-08-15 13:35 UTC
```shell
dfdl/df-20190815204305/df_osx/dfhack ; exit;
dyld: could not load inserted library './hack/libdfhack.dylib' because no suitable image found.  Did find:
	./hack/libdfhack.dylib: mach-o, but wrong architecture
	./hack/libdfhack.dylib: stat() failed with errno=1

dfdl/df-20190815204305/df_osx/dfhack: line 15: 41475 Abort trap: 6           DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"
```

```libdfhack.dylib``` is a link to 10.1MB `libdfhack.1.0.0.dylib`

I've tried to inspect it with `lipo`:

```shell
% lipo -infodfdl/df-20190815204305/df_osx/hack/libdfhack.dylib                            
Non-fat file:dfdl/df-20190815204305/df_osx/hack/libdfhack.dylib is architecture: i386
% lipo -infodfdl/df-20190815204305/df_osx/hack/libdfhack-client.dylib                    Non-fat file:dfdl/df-20190815204305/df_osx/hack/libdfhack-client.dylib is architecture: i386

% lipo -infodfdl/df-20190815204305/df_osx/libs/libgcc_s.1.dylib                    Architectures in the fat file:dfdl/df-20190815204305/df_osx/libs/libgcc_s.1.dylib are: i386 x86_64
```

I'm installing things using https://github.com/jipumarino/dfdl

**Comment by lethosor** [comment] 2019-08-15 13:37
You need to install the 64-bit version of DFHack if you're running the 64-bit version of DF.

**Comment by lethosor** [comment] 2019-08-15 13:45
Closing as this appears to be a dfdl issue: https://github.com/jipumarino/dfdl/issues/4

**Comment by linonetwo** [comment] 2019-08-15 13:45
Thank you for the fast reply, I tried rerun `dfdl` for `OSX-64` and it worked this time!

```shell
2) dfhack-0.44.12-r2-OSX-64-gcc-7.3.0.tar.bz2
1) dfhack-0.44.12-r2-OSX-32-gcc-7.3.0.tar.bz2
2
```

**Closed by lethosor** 2019-08-15 13:45 UTC

**Comment by lethosor** [comment] 2019-08-15 13:47
Oh, it gives you options for which one to install? I thought it was just selecting the first match it found. (I didn't try it out, admittedly.)
DF and DFHack's download pages are sorted differently, which is probably the root cause of that.
