### ISSUE TITLE
Automaterials: Will build constructed floor over existing constructed floor with 'box select'

### ISSUE THREAD

**Issue by DoctorVanGogh** [DFHack/dfhack#721] opened 2015-11-02 02:18 UTC
I noticed a bug in automaterials:

In 'default' mode the game does not allow constructing floor over already constructed floor - you get an 'invalid' indicator and a 'Construction present' error:

![floor-on-floor-default](https://cloud.githubusercontent.com/assets/324067/10872193/918c3462-80fc-11e5-88c3-69618ab7f3ea.png)

If you use automaterials' "box select" setting, it will happily create construction jobs over the already existing constructed floor:
![floor-on-floor-box-select](https://cloud.githubusercontent.com/assets/324067/10872202/b753ad56-80fc-11e5-901e-9daa997c0f0a.png) ![floor-on-floor-box-select-final](https://cloud.githubusercontent.com/assets/324067/10872203/ba9f92d6-80fc-11e5-8ad9-2c4ab6d026ad.png)

Automaterials *should* exclude existing construction (as it does with walls for example).

This bug stems from the fact, that automaterials 
1. Does not check the base tiletypes
2. Only checks if the layer below is a wall - *not* if it is a __constructed__ wall
3. And even if a check for a __constructed wall__ in the layer below is made, we'd still be able to rebuild a constructed floor on top of that ad infinitum

I've hacked together a small fix for 1 (and 2) in 092979f3624d9029c14d77688a85746aa1a245ad (also I renamed some variables to avoid confusion due to variable name reuse). With this I think checking for 2 becomes unnecessary since the 'constructed floor over natural floor' situation gets caught by it.

![floor-on-floor-partialfix](https://cloud.githubusercontent.com/assets/324067/10873105/5e55b4fc-810f-11e5-9a2a-500759391d2e.png)
It's mostly some cannibalized code from `probe` - no idea if there are better ways to query the base tiletype than using MapCache.

---

(3) is a **really really** nasty can of worms. I don't see any _simple_ way to prevent building an infinite number of constructed floors above a constructed wall, because the tile types & shapes are completely identical if it is just a wall, or a wall with a floor on top. 

Currently the __only__ differentiating feature I see is in `d`, `n` ("Designate", "Remove Construction"): Tiles where automaterials _should_ allow floor construction are colored red, tiles where it should disallow it are colored green. I don't know if there's a way to query that information, or if we could try designating tiles, see what takes, and work with that, or if the game happily takes invalid designations.

**Comment by lethosor** [comment] 2015-11-02 02:57
There ought to be a way to determine whether a tile has a constructed floor on it or just has a floor from a constructed wall below, although I haven't investigated.

**Comment by DoctorVanGogh** [comment] 2015-11-02 03:02
The result of `probe`for an empty tile above a constructed wall and a tile with a constructed floor above a constructed wall are exactly the same ;)

**Comment by PeridexisErrant** [comment] 2015-11-02 03:24
Duplicate of #613, I think.

**Comment by lethosor** [comment] 2015-11-02 03:28
I prefer this one, although part 3 is probably the most problematic, and I'd like to be able to fix that.

**Comment by DoctorVanGogh** [comment] 2015-11-06 16:57
I've found another nasty use case that needs to get correctly processed by whatever new check ends up being implemented:

I had a constructed ramp on top of a constructed wall outdoors. That ramp was wet - then came winter ;) The ramp became an ice block, which thawed in spring, removing the ramp. A simple 'Mouse over' shows the tile as a constructed floor (no ramp there).

`probe` before deconstruction due to ice:
```
tiletype: 514 = constructed ramp
Class     :    9 RAMP
Material  :    7 CONSTRUCTION
Special   :   -1 NONE
Variant   :   -1 NONE
Direction : --------

static: 514 = constructed ramp
Class     :    9 RAMP
Material  :    7 CONSTRUCTION
Special   :   -1 NONE
Variant   :   -1 NONE
Direction : --------

base: 514 = constructed ramp
Class     :    9 RAMP
Material  :    7 CONSTRUCTION
Special   :   -1 NONE
Variant   :   -1 NONE
Direction : --------
```
`probe` after deconstruction:
```
tiletype: 489 = constructed floor
Class     :    1 FLOOR
Material  :    7 CONSTRUCTION
Special   :    3 SMOOTH
Variant   :   -1 NONE
Direction : --------

static: 489 = constructed floor
Class     :    1 FLOOR
Material  :    7 CONSTRUCTION
Special   :    3 SMOOTH
Variant   :   -1 NONE
Direction : --------

base: 514 = constructed ramp
Class     :    9 RAMP
Material  :    7 CONSTRUCTION
Special   :   -1 NONE
Variant   :   -1 NONE
Direction : --------
```

As you can see, the base tile type still shows the ramp  - so we actually can't use that (as I did in my partial fix) to check for existing construction.

**Comment by DoctorVanGogh** [comment] 2015-11-06 18:17
Updated my pull request #727.

**Closed** 2015-11-07 01:24 UTC
Labels: automaterial, bug
