### ISSUE TITLE
Dwarfvet crashes the game after enabled and unpaused

### ISSUE THREAD

**Issue by alfalfascout** [DFHack/dfhack#1227] opened 2018-02-11 17:23 UTC
Here's what I got in the console:

```
DFHack is ready. Have a nice day!
DFHack version 0.44.05-r1 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]# dwarfvet report
Current animal hospitals are:
  at x1: 68, x2%d, y1: 76, y2: 62, z: 70
[DFHack]# dwarfvet enable
dwarfvet enabled!
Populating hospital cache:
[DFHack]# .../Games/df_osx_44.05/dfhack: line 15: 18628 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

This is my first time attempting to use dwarfvet. My fortress is about 3 years old. Every time I turn on the fort, set my hospital to an animal training zone, enable dwarfvet, and unpause... my game crashes a few seconds afterwards. 

Is there anything I can do to fix this? Do you need more information?

**Comment by lethosor** [comment] 2018-02-13 16:17
I get this:
```
[DFHack]# dwarfvet enable
dwarfvet enabled!
Populating hospital cache:
  Found animal hospital 585  at x1: 31, y1: 47 from valid hospital list
```
If it works in another world, can you upload the problematic world?

**Comment by lethosor** [comment] 2018-02-14 14:27
Ok, I couldn't find a hospital at those x/y coordinates (there was a bug I just fixed with it not printing the z coordinate correctly), but creating a new one caused a crash, so I'll look into it. Thanks!

**Comment by lethosor** [comment] 2018-02-14 15:17
I think the issue is the beds in the animal hospital, but haven't verified it. You could try deconstructing them, or disabling the training or hospital aspects of that zone and making a new zone.

**Comment by lethosor** [comment] 2018-02-16 07:37
@NCommander this patch fixes the crash, at least, but probably not correctly:
```diff
diff --git a/plugins/dwarfvet.cpp b/plugins/dwarfvet.cpp
index 46247bb8..604f399a 100644
--- a/plugins/dwarfvet.cpp
+++ b/plugins/dwarfvet.cpp
@@ -135,8 +135,8 @@ AnimalHospital::AnimalHospital(df::building * building, color_ostream &out) {
     z = building->z;
 
     // Determine how many spots we have for animals
-    this->length = x2-x1;
-    this->height = y2-y1;
+    this->length = x2-x1+1; // Note below
+    this->height = y2-y1+1;
 
     // And calculate the hospital!
     this->calculateHospital(true, out);
@@ -321,8 +321,8 @@ void AnimalHospital::calculateHospital(bool force, color_ostream &out) {
 
         spot_cur += building_offset_x;
         /* Start marking! */
-        for (int i = 0; i != building_height; i++) {
-            for (int j = 0; j != building_length; j++) {
+        for (int i = 0; i < building_height; i++) {
+            for (int j = 0; j < building_length; j++) {
                 spots_in_use[spot_cur+j] = true;
             }
 
```
I'm not sure if the first chunk is necessary, but it looked wrong.

**Comment by alfalfascout** [comment] 2018-02-16 15:37
Do you have an estimate for when the next release will be available, with the final version of the fix for this issue?

**Comment by lethosor** [comment] 2018-02-16 16:53
I'm hoping to get one out in a couple days, but no idea about a "final" fix. Those changes should stop it from crashing, but it might treat your animal hospital as 1x1 because of all the beds, so I think your best bet for now is to remove those.

**Comment by alfalfascout** [comment] 2018-02-16 23:57
Why does having beds in my hospital make it 1x1?

**Comment by lethosor** [comment] 2018-02-17 00:14
I don't know. I didn't write it. It looks to me like it's calculating the largest rectangle within the zone that doesn't have any buildings in it. It might end up as 1x6 or something.

**Comment by alfalfascout** [comment] 2018-02-17 00:19
That's so strange. Hospitals need beds and traction benches and tables.

**Comment by lethosor** [comment] 2018-02-17 00:35
You'd have to ask @NCommander. I could try to work around that restriction for beds, but I don't think animals would use them.

**Comment by NCommander** [comment] 2018-02-17 02:10
I'm alive. As far as I can tell, what's actually required to get something treated by the hospital is it's resting in a hospital zone.

This is probably a change in DF as it didn't crash when it tried to drop a unit on a bed back in 0.40 when I coded it; the array likely needs to figure out inelligable spots and simply dump them on the floor or figure out whatever magic is needed when a unit is properly "in bed" so to speak.

**Comment by lethosor** [comment] 2018-02-17 03:03
The second part of my patch fixes the crash. The building length or width is negative, which results in an infinite loop writing to increasing indices in a vector. I don't think that's a DF change.

**Comment by lethosor** [comment] 2018-02-22 04:06
The crash should be fixed. Feel free to open another report if you notice any other issues with that hospital. I haven't had much time to figure out what else could be wrong with it.

**Closed by lethosor** 2018-02-22 04:06 UTC
Labels: bug, crash
